#! /bin/bash

XVFB=/usr/bin/Xvfb
XVFBARGS=":{{ xvfb_display_number }} -screen 0 1024x768x24 -fbdir /var/run -ac"
PIDFILE=/var/run/xvfb.pid

case "$1" in
    start)
        echo -n "Starting virtual X frame buffer: Xvfb"
        start-stop-daemon --start --quiet --pidfile $PIDFILE --make-pidfile --background --exec $XVFB -- $XVFBARGS
        echo "."
        ;;
    stop)
        echo -n "Stopping virtual X frame buffer: Xvfb"
        start-stop-daemon --stop --quiet --pidfile $PIDFILE
        rm $PIDFILE
        echo "."
        ;;
    restart)
        $0 stop
        $0 start
        ;;
    status)
        RUNINGXVFB=$(ps aux | grep [X]vfb)
        if [[ "$RUNINGXVFB" == *Xvfb*screen* ]]
        then
            echo 'Xvfb is running'
        else
            echo 'Xvfb is not running'
        fi
        ;;
    *)
        echo "Usage: /etc/init.d/xvfb {start|stop|restart}"
        exit 1
esac

exit 0
