---

- name: check if ruby installed
  shell: ls /opt/rubies
  register: ruby_installed

- name: Install ruby dependencies
  apt: name={{item}} state=latest update_cache=yes
  sudo: yes
  with_items:
    - build-essential
    - git
    - libcurl4-openssl-dev
    - libreadline-dev
    - libssl-dev
    - libxml2-dev
    - libxslt1-dev
    - zlib1g-dev
    - libpq-dev
  when: ruby_installed.stdout.find(ruby_full_version) == -1

- name: Download ruby
  get_url: url={{ ruby_url }} dest=/tmp/ruby-{{ ruby_full_version }}.tar.gz
  when: ruby_installed.stdout.find(ruby_full_version) == -1

- name: Extract ruby
  command: tar -zxf /tmp/ruby-{{ ruby_full_version }}.tar.gz -C /tmp
  when: ruby_installed.stdout.find(ruby_full_version) == -1

- name: Make, configure, and install ruby
  command: $item chdir=/tmp/ruby-{{ ruby_full_version }}
  sudo: True
  with_items:
    - ./configure --prefix=/opt/rubies/ruby-{{ ruby_full_version }}
    - make
    - sudo make install
  when: ruby_installed.stdout.find(ruby_full_version) == -1

- name: Install bundler
  command: sudo /opt/rubies/ruby-{{ ruby_full_version }}/bin/gem install bundler
  when: ruby_installed.stdout.find(ruby_full_version) == -1